### ISSUE TITLE
Localstack is always v3.2.0

### ISSUE THREAD

**Issue by mherger** [HarshCasper/setup-localstack#24]
I'm using pretty much the example integration in my workflow:

```
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@v0.2.0
        with:
          image-tag: latest
          install-awslocal: true
          use-pro: false
``` 

But no matter what I put as the `image-tag`, I'd always get v3.2.0, which doesn't work for us due to https://github.com/localstack/localstack/issues/10621. So I must use v3.4.0 (or 2.2.0 - which we've used before).

FWIW: I'm seeing similar odd behaviour installing a specific version using `pip3 install localstack==2.2.0`. It would seemingly install that version, but I'd still get the above issue.
